### ISSUE TITLE
Can ResNet18 work?

### ISSUE THREAD

**Issue by rain152** [liuyugeng/baadd#2]

**Comment by liuyugeng** [comment]
No. As we mentioned in the Limitation Section in our paper, neither the DD nor the DC algorithm can utilize the model with the BatchNorm (BN) layer as an upstream model.

**Comment by rain152** [comment]
> No. As we mentioned in the Limitation Section in our paper, neither the DD nor the DC algorithm can utilize the model with the BatchNorm (BN) layer as an upstream model.

Thanks!
