### ISSUE TITLE
requiry about the weight of DD

### ISSUE THREAD

**Issue by wuyu-1** [liuyugeng/baadd#4]
When I run backdoor on DD, I cannot return the weights of the models. 
And when I use the saved dataset to evaluate it again, I cannot get the same results as the training log.

**Comment by liuyugeng** [comment]
No, you can't directly return any weights because the DD code splits the weights into a list. I think this is because they use a very early version of PyTorch.

**Comment by liuyugeng** [comment]
I think the parameters are saved in the ```results.pth```. You can load it as the ```step```.

For instance,
```
steps = torch.load(os.path.join(data_path, 'results.pth'))
steps = [(d.to(state.device), l.to(state.device), lr.to(state.device)) for (d, l, lr) in steps]
```

And evaluate it by using [this](https://github.com/liuyugeng/baadd/blob/cade4d2b2925567c34d861ac69a29bdeb99543c8/DD/basics.py#L274).

**Comment by liuyugeng** [comment]
I will close this issue. Feel free to open it again.
