### ISSUE TITLE
about the trigger

### ISSUE THREAD

**Issue by Guncuke** [liuyugeng/baadd#5]
Hello author!
when I run this code, I found that the number of the tigger is out of 0~255, Is this normal? thanks!

**Comment by liuyugeng** [comment]
It is normal. We didn't do any regularization about the values.

**Comment by Guncuke** [comment]
thanks

**Comment by Guncuke** [comment]
I found that on the normalized image dataset, the final trigger even reached 1000+, which is high enough to get an accuracy of 100 even without top-k fine-tuning

**Comment by liuyugeng** [comment]
Yes, maybe this is a reason, but you can regularize the trigger in a range and see the ASR results.
