### ISSUE TITLE
about ConvNet net_norm

### ISSUE THREAD

**Issue by Guncuke** [liuyugeng/baadd#6]
Hello author!
I found that the net_norm in the original source code is net_norm, but here it change to 'none'
in CIFAR10 and other datasets, it's hard to convergence, the condensed dataset is poor.
Thanks

**Comment by liuyugeng** [comment]
Hi, as we mentioned in the paper, using BN layer for DD and DC is wrong. Therefore, in our paper, we didn't use any types of norm layer.
